//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Collection : TestItemBase
{
	public virtual int host
	{
		get;
		set;
	}

	public virtual List<Project> projects
	{
		get;
		set;
	}

}

