//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestSuite : TestItemBase
{
    public int Id
    {
        get;
        set;
    }

    public string Name
    {
        get;
        set;
    }

	public virtual List<TestCase> TestCases
	{
		get;
		set;
	}

	public virtual string Description
	{
		get;
		set;
	}

	public virtual int Parent
	{
		get;
		set;
	}

	public virtual TestPlan TestPlan
	{
		get;
		set;
	}

}

