//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestStep : TestItemBase, StepBase
{
    public int Id
    {
        get;
        set;
    }

    public string Name
    {
        get;
        set;
    }

    public string Result
    {
        get;
        set;
    }
	public virtual TestCase TestCase
	{
		get;
		set;
	}

	public virtual TestSharedStep TestSharedStep
	{
		get;
		set;
	}

}

