//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestPlan : TestItemBase
{
    public int Id
    {
        get;
        set;
    }

    public string Name
    {
        get;
        set;
    }
	public virtual List<TestSuite> Suites
	{
		get;
		set;
	}

	public virtual Project Project
	{
		get;
		set;
	}

}

