//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestCase : TestItemBase
{
	public virtual List<TestStep> steps
	{
		get;
		set;
	}

	public virtual string description
	{
		get;
		set;
	}

	public virtual List<Attachment> attachments
	{
		get;
		set;
	}

	public virtual List<SourceFile> link
	{
		get;
		set;
	}

	public virtual List<Tag> tags
	{
		get;
		set;
	}

	public virtual TestSuite TestSuite
	{
		get;
		set;
	}

}

