//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestCase : TestItemBase
{
    public int Id
    {
        get;
        set;
    }

    public string Name
    {
        get;
        set;
    }
	public virtual List<TestStep> Steps
	{
		get;
		set;
	}

	public virtual string Description
	{
		get;
		set;
	}

	public virtual List<Attachment> Attachments
	{
		get;
		set;
	}

	public virtual List<RepositoryFile> Link
	{
		get;
		set;
	}

	public virtual List<Tag> Tags
	{
		get;
		set;
	}

	public virtual TestSuite TestSuite
	{
		get;
		set;
	}

}

