USE [master]
GO

/****** Object:  Database [testflow]    Script Date: 12/1/2014 12:32:31 AM ******/
CREATE DATABASE [testflow]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testflow', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\testflow.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'testflow_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\testflow_log.ldf' , SIZE = 4096KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [testflow] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testflow].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testflow] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testflow] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testflow] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testflow] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testflow] SET ARITHABORT OFF 
GO

ALTER DATABASE [testflow] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testflow] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [testflow] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testflow] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testflow] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testflow] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testflow] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testflow] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testflow] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testflow] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testflow] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testflow] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testflow] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testflow] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testflow] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testflow] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testflow] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testflow] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testflow] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [testflow] SET  MULTI_USER 
GO

ALTER DATABASE [testflow] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testflow] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testflow] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testflow] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [testflow] SET  READ_WRITE 
GO

