//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_Collection_Types
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Type_Id { get; set; }
        public string Name { get; set; }
    }
}
