using DataStore.Adapters.Composites;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IDataStoreAdapter 
{
    IProjectHelper Projects { get; }
    ITestPlanHelper TestPlans { get; }
    ISuiteHelper Suites { get; }
    ITestCaseHelper TestCases { get; }
    IStepHelper Steps { get; }
}

