//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_ExternalIds
    {
        public int External_Id { get; set; }
        public int Id { get; set; }
        public int Type { get; set; }
        public int Internal_Id { get; set; }
    
        public virtual TF_ItemType TF_ItemType { get; set; }
    }
}
