//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_ItemType
    {
        public TF_ItemType()
        {
            this.TF_ExternalIds = new HashSet<TF_ExternalIds>();
        }
    
        public int Type_Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TF_ExternalIds> TF_ExternalIds { get; set; }
    }
}
