//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ServiceFacade
{
	private DataStoreController dataStore
	{
		get;
		set;
	}

	private User user
	{
		get;
		set;
	}

	public virtual void getProjects()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getTestPlan(object int testPlanId)
	{
		throw new System.NotImplementedException();
	}

}

