//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Text;

public class ServiceFacade
{
	private DataStoreController dataStore
	{
		get;
		set;
	}

    public ServiceFacade(IPrincipal user)
    {
        dataStore = new DataStoreController(user);
    }

	private IPrincipal user
	{
		get;
		set;
	}

	public List<Project> getProjects()
	{
        return dataStore.getProjects();
	}

	public virtual void getTestPlan(int testPlanId)
	{
		throw new System.NotImplementedException();
	}

    public List<TestPlan> getTestPlans(int projectId)
    {
        return dataStore.getTestPlans(projectId);
    }
    public TestPlan getTestPlan(int projectId, int id)
    {
        return dataStore.getTestPlan(projectId, id);
    }

    public void editTestItem(TestItemBase testItem)
    {
        dataStore.editTestItem(testItem);
    }

    public void createTestPlan(int projectId, string name)
    {
        dataStore.createTestPlan(projectId, name);
    }

    // collection management metods

    public void EditCollection(Collection collection)
    {
        dataStore.EditCollection(collection);
    }

    public Collection GetCollection(int id)
    {
        return dataStore.GetCollection(id);
    }

    public List<Collection> GetCollections()
    {
        return dataStore.GetCollections();
    }

    public void CreateCollection(Collection collection, int type)
    {
        dataStore.CreateCollection(collection, type);
    }
}

