//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Text;

public class ServiceFacade
{
	private DataStoreController dataStore
	{
		get;
		set;
	}

    public ServiceFacade()
    {
        dataStore = new DataStoreController();
    }

	private IPrincipal user
	{
		get;
		set;
	}

	public List<Project> getProjects()
	{
        return dataStore.getProjects();
	}

	public virtual void getTestPlan(int testPlanId)
	{
		throw new System.NotImplementedException();
	}

}

