//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConfigurationStore
{
	private List<DataStoreAdapter> adapters
	{
		get;
		set;
	}

	public virtual List<DataStoreAdapter> getUserConfiguration()
	{
        TfsDataStore tfsStore = new TfsDataStore();
        tfsStore.Name = "Test TFS Collection";
        tfsStore.Host = new Uri("http://tc-dev.cis.fiu.edu:8080/tfs/DefaultCollection");
        List<DataStoreAdapter> dList = new List<DataStoreAdapter>();
        dList.Add(tfsStore);
        return dList;
	}

	public virtual void getTestPlanConfiguration(TestPlan testPlan)
	{
		throw new System.NotImplementedException();
	}

}

