//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface DataStoreAdapter 
{
	string host { get;set; }

	string name { get;set; }

	ICredentials authentication { get;set; }

	DataStoreController DataStoreController { get;set; }

	void insertItem(object User user, object TestPlan testPlan, object TestModel testElement);

	void editItem(object User user, object TestItemBase item);

	void removeItem(object User user, object TestStep step);

}

