//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Principal;
using System.Text;

public class DataStoreController
{
	private List<DataStoreAdapter> dataStores
	{
		get;
		set;
	}

    public DataStoreController()
    {
        ConfigurationStore cStore = new ConfigurationStore();
        dataStores = cStore.getUserConfiguration();
    }

	public virtual void insertItem(IPrincipal user, TestPlan testPlan, TestItemBase testElement)
	{
		throw new System.NotImplementedException();
	}

	public void insertNewFile(IPrincipal user, TestPlan testPlan, string file)
	{
		throw new System.NotImplementedException();
	}

	public List<Project> getProjects()
	{
        List<Project> projects = new List<Project>();
        foreach (DataStoreAdapter dsa in dataStores)
        {
            List<Project> temp = dsa.getProjects();
            projects = projects.Concat(temp).ToList();
        }
           
        return projects;
	}

    public List<TestPlan> getTestPlans(string projectName)
    {
        List<TestPlan> projects = new List<TestPlan>();
        foreach (DataStoreAdapter dsa in dataStores)
        {
            List<TestPlan> temp = dsa.getPlans(projectName);
            projects = projects.Concat(temp).ToList();
        }

        return projects;
    }

    public TestPlan getTestPlan(string projectName, int id)
    {
        TestPlan plan = null;
        foreach (DataStoreAdapter dsa in dataStores)
        {
            plan = dsa.getPlan(projectName, id);
            if (plan != null)
                break;
        }

        return plan;
    }

}

