//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface DataStoreAdapter 
{
	Uri Host { get;set; }

	string Name { get;set; }

	void insertItem(TestPlan testPlan, TestItemBase testElement);

	void editItem(TestItemBase item);

	void removeItem(TestStep step);

    List<Project> getProjects();

}

