//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FileStore
{
	public virtual string Path
	{
		get;
		set;
	}

	public virtual void getFiles(object TestPlanElement)
	{
		throw new System.NotImplementedException();
	}

}

