//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestFlowDataStore : DataStoreAdapter
{
	public virtual void insertItem(object User user, object TestPlan testPlan, object TestModel testElement)
	{
		throw new System.NotImplementedException();
	}

	public virtual void editItem(object User user, object TestItemBase item)
	{
		throw new System.NotImplementedException();
	}

	public virtual void removeItem(object User user, object TestStep step)
	{
		throw new System.NotImplementedException();
	}

}

