//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Text;

public class TestFlowDataStore : DataStoreAdapter
{
    public string Name
    {
        get;
        set;
    }
    public Uri Host
    {
        get;
        set;
    }

	public virtual void insertItem(TestPlan testPlan, TestItemBase testElement)
	{
		throw new System.NotImplementedException();
	}

	public virtual void editItem(TestItemBase item)
	{
		throw new System.NotImplementedException();
	}

	public virtual void removeItem(TestStep step)
	{
		throw new System.NotImplementedException();
	}

    public List<Project> getProjects()
    {
        throw new System.NotImplementedException();
    }
}

