using Microsoft.TeamFoundation.Client;
using Microsoft.TeamFoundation.WorkItemTracking.Client;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Text;

public class TfsDataStore : DataStoreAdapter
{
    public string Name
    {
        get;
        set;
    }
    public Uri Host
    {
        get;
        set;
    }
	public virtual void insertItem(TestPlan testPlan, TestItemBase testElement)
	{
		throw new System.NotImplementedException();
	}

	public virtual void editItem(TestItemBase item)
	{
		throw new System.NotImplementedException();
	}

	public virtual void removeItem(TestStep step)
	{
		throw new System.NotImplementedException();
	}

    public List<Project> getProjects()
    {
        var tpc = TfsTeamProjectCollectionFactory.GetTeamProjectCollection(Host);
        ICredentials crds = new NetworkCredential("TFS", "test123");

        tpc.Credentials = crds;

        var workItemStore = new WorkItemStore(tpc);
        // returns list of tfs projects
        var tfsProjectList = (from Microsoft.TeamFoundation.WorkItemTracking.Client.Project pr in workItemStore.Projects select pr).ToList();

        // convert list into test flow project list
        List<Project> projectList = new List<Project>();
        foreach(Microsoft.TeamFoundation.WorkItemTracking.Client.Project tfsProj in tfsProjectList)
        {
            Project proj = new Project();
            proj.Name = tfsProj.Name;
            proj.Id = tfsProj.Id;
            proj.Store = Name;
            projectList.Add(proj);
        }

        return projectList;
    }
}

